name: ClojureCI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: lein deps
      - name: Run tests
        run: lein cloverage

  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: lein deps
      - run: lein check
      - run: lein kibit
      # - run: lein cljmft check

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: ENV=prod lein uberjar
      - name: copy file via ssh
        uses: maddox/actions/ssh@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          PRIVATE_KEY: ${{ secrets.KEY }}
        with:
          source: "./target/social-stats-bot-0.0.1-SNAPSHOT-standalone.jar"
          target: ",/home/neiro/social-stats-bot.jar"
